import type { ArticleSummary } from "../types/summary.js";
import type { SlackMessage, SlackBlock } from "../types/slack.js";

const SENTIMENT_EMOJI: Record<string, string> = {
  positive: ":chart_with_upwards_trend:",
  negative: ":chart_with_downwards_trend:",
  neutral: ":bar_chart:",
};

const CATEGORY_EMOJI: Record<string, string> = {
  AI: ":robot_face:",
  ML: ":brain:",
  LLM: ":speech_balloon:",
  Robotics: ":mechanical_arm:",
  Other: ":bulb:",
};

function getSentimentEmoji(sentiment: string): string {
  return SENTIMENT_EMOJI[sentiment] || ":bar_chart:";
}

function getCategoryEmoji(category: string): string {
  return CATEGORY_EMOJI[category] || ":bulb:";
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("ja-JP", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function formatSummaryBlock(summary: ArticleSummary): SlackBlock[] {
  const blocks: SlackBlock[] = [];

  // タイトル
  blocks.push({
    type: "header",
    text: {
      type: "plain_text",
      text: summary.title.slice(0, 150), // Slack制限
      emoji: true,
    },
  });

  // メタ情報
  blocks.push({
    type: "section",
    fields: [
      {
        type: "mrkdwn",
        text: `*Category:* ${getCategoryEmoji(summary.category)} ${summary.category}`,
      },
      {
        type: "mrkdwn",
        text: `*Sentiment:* ${getSentimentEmoji(summary.sentiment)} ${summary.sentiment}`,
      },
    ],
  });

  // 要約
  blocks.push({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `*Summary:*\n${summary.summary}`,
    },
  });

  // キーポイント
  if (summary.keyPoints.length > 0) {
    const keyPointsText = summary.keyPoints
      .map((point) => `• ${point}`)
      .join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Key Points:*\n${keyPointsText}`,
      },
    });
  }

  // リンクボタン
  if (summary.url) {
    blocks.push({
      type: "actions" as const,
      elements: [
        {
          type: "button",
          text: {
            type: "plain_text",
            text: "Read Article",
            emoji: true,
          } as { type: "plain_text"; text: string; emoji?: boolean },
          url: summary.url,
        } as { type: string; text?: { type: string; text: string; emoji?: boolean }; url?: string },
      ],
    } as SlackBlock);
  }

  // 区切り線
  blocks.push({ type: "divider" });

  return blocks;
}

export function formatDailySummary(
  summaries: ArticleSummary[],
  date?: Date
): SlackMessage {
  const targetDate = date || new Date();
  const blocks: SlackBlock[] = [];

  // ヘッダー
  blocks.push({
    type: "header",
    text: {
      type: "plain_text",
      text: `:newspaper: AI News Daily Summary`,
      emoji: true,
    },
  });

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `${formatDate(targetDate)} | ${summaries.length} articles`,
      },
    ],
  } as SlackBlock);

  blocks.push({ type: "divider" });

  // 各記事のブロック
  for (const summary of summaries) {
    blocks.push(...formatSummaryBlock(summary));
  }

  // フッター
  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: "_Generated by AI News Pipeline_ :robot_face:",
      },
    ],
  } as SlackBlock);

  return {
    text: `AI News Daily Summary - ${summaries.length} articles`,
    blocks,
    unfurl_links: false,
    unfurl_media: false,
  };
}

export function formatErrorNotification(
  errors: Array<{ title: string; error: string }>
): SlackMessage {
  const blocks: SlackBlock[] = [];

  blocks.push({
    type: "header",
    text: {
      type: "plain_text",
      text: ":warning: Pipeline Errors",
      emoji: true,
    },
  });

  blocks.push({ type: "divider" });

  for (const { title, error } of errors.slice(0, 10)) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*${title.slice(0, 100)}*\n\`${error}\``,
      },
    });
  }

  if (errors.length > 10) {
    blocks.push({
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `_...and ${errors.length - 10} more errors_`,
        },
      ],
    } as SlackBlock);
  }

  return {
    text: `Pipeline encountered ${errors.length} errors`,
    blocks,
  };
}
