import Link from "next/link";
import { getStats, getArchiveMonths, getAllArchiveData } from "@/lib/archive";

export default function ArchivePage() {
  const stats = getStats();
  const months = getArchiveMonths();
  const archives = getAllArchiveData();

  const formatMonth = (monthStr: string) => {
    const [year, month] = monthStr.split("-");
    return `${year}年${parseInt(month)}月`;
  };

  return (
    <>
      <header className="header">
        <div className="container header-content">
          <h1 className="logo">
            <Link href="/" style={{ textDecoration: "none", color: "inherit" }}>
              <span>AI</span> News Pipeline
            </Link>
          </h1>
          <Link
            href="/"
            style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}
          >
            ← 最新ニュースへ
          </Link>
        </div>
      </header>

      <main className="container">
        <h2 style={{ marginBottom: "1.5rem" }}>アーカイブ</h2>

        {stats && (
          <div
            style={{
              backgroundColor: "var(--card-bg)",
              padding: "1.5rem",
              borderRadius: "0.5rem",
              marginBottom: "2rem",
              border: "1px solid var(--border-color)",
            }}
          >
            <h3 style={{ marginBottom: "1rem", fontSize: "1rem" }}>統計情報</h3>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
                gap: "1rem",
              }}
            >
              <div>
                <div style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>
                  総記事数
                </div>
                <div style={{ fontSize: "1.5rem", fontWeight: "bold" }}>
                  {stats.totalArticles}
                </div>
              </div>
              <div>
                <div style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>
                  アクティブ
                </div>
                <div style={{ fontSize: "1.5rem", fontWeight: "bold" }}>
                  {stats.activeArticles}
                </div>
              </div>
              <div>
                <div style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>
                  アーカイブ済み
                </div>
                <div style={{ fontSize: "1.5rem", fontWeight: "bold" }}>
                  {stats.archivedArticles}
                </div>
              </div>
            </div>
          </div>
        )}

        {months.length > 0 ? (
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
              gap: "1rem",
            }}
          >
            {archives.map((archive) => (
              <div
                key={archive.month}
                style={{
                  backgroundColor: "var(--card-bg)",
                  padding: "1.5rem",
                  borderRadius: "0.5rem",
                  border: "1px solid var(--border-color)",
                }}
              >
                <h3 style={{ marginBottom: "0.5rem" }}>
                  {formatMonth(archive.month)}
                </h3>
                <div style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>
                  {archive.articles.length}件の記事
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="empty-state">
            <p>アーカイブはまだありません</p>
            <p style={{ color: "var(--text-secondary)", marginTop: "0.5rem" }}>
              30日以上経過した記事が自動的にアーカイブされます
            </p>
          </div>
        )}
      </main>

      <footer className="footer">
        <div className="container">
          <p>Generated by AI News Pipeline</p>
        </div>
      </footer>
    </>
  );
}
