import { test, expect } from "@playwright/test";

test.describe("AI News Pipeline", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/");
  });

  test("should display the page title", async ({ page }) => {
    await expect(page).toHaveTitle(/AI News/);
  });

  test("should display the header with logo", async ({ page }) => {
    const header = page.locator("header");
    await expect(header).toBeVisible();
    await expect(header.locator("h1")).toContainText("AI News Pipeline");
  });

  test("should display the footer", async ({ page }) => {
    const footer = page.locator("footer");
    await expect(footer).toBeVisible();
    await expect(footer).toContainText("Generated by AI News Pipeline");
    await expect(footer).toContainText("Powered by Hacker News API & Claude AI");
  });

  test("should display news articles", async ({ page }) => {
    const newsItems = page.getByTestId("news-item");
    await expect(newsItems.first()).toBeVisible();
  });

  test("news article should have required elements", async ({ page }) => {
    const firstArticle = page.getByTestId("news-item").first();
    await expect(firstArticle).toBeVisible();

    // Title should be visible
    const title = firstArticle.getByTestId("news-title");
    await expect(title).toBeVisible();

    // Summary should be visible
    const summary = firstArticle.locator(".news-summary");
    await expect(summary).toBeVisible();

    // Category badge should be visible
    const category = firstArticle.locator(".news-category");
    await expect(category).toBeVisible();

    // Date should be visible
    const date = firstArticle.getByTestId("news-date");
    await expect(date).toBeVisible();
  });

  test("should have working external links", async ({ page }) => {
    const articleLink = page.getByTestId("news-title").first().locator("a");

    // Check if link exists and has target="_blank"
    if (await articleLink.count() > 0) {
      await expect(articleLink).toHaveAttribute("target", "_blank");
      await expect(articleLink).toHaveAttribute("rel", "noopener noreferrer");
    }
  });
});
