import { NewsList } from "@/components/NewsList";
import newsData from "../../data/news.json";
import type { NewsData } from "@/types/news";

export default function Home() {
  const data = newsData as NewsData;

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("ja-JP", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  return (
    <>
      <header className="header">
        <div className="container header-content">
          <h1 className="logo">
            <span>AI</span> News Pipeline
          </h1>
          <span style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>
            Last updated: {formatDate(data.generatedAt)}
          </span>
        </div>
      </header>

      <main className="container">
        <NewsList articles={data.articles} />
      </main>

      <footer className="footer">
        <div className="container">
          <p>Generated by AI News Pipeline</p>
          <p style={{ marginTop: "0.5rem" }}>
            Powered by Hacker News API & Claude AI
          </p>
        </div>
      </footer>
    </>
  );
}
